### PR TITLE
Add owo for inclusion

### PR DESCRIPTION
**Pull request by PatrickAlphaC**
If we want this package to be more inclusive to the furry community, we might want to think about catering to them in the tests. I humbly offer this improvement to the package.

```
const { owoify } = require("owoifyx")

console.log(owoify("Hello! Let's run some tests"))
```
To output:

```
Hewwo (*^ω^) Wet's wun some tests
```

When you run tests.

### CODE REVIEW

**Comment by james-work-account** [comment]
<details>
<summary>Please also add to the smoke tests. This important change needs to be in _**all**_ tests.</summary>

(Also running the full tests takes _way_ too long.)
</details>

**Comment by PatrickAlphaC** [comment]
@james-work-account - good call! I can't believe I forgot that.

Or should I say...

good caww (◕ᴥ◕) I can't bewieve I fowgot that

**Comment by PatrickAlphaC** [comment]
updated as mentioned on the smoke tests

**Review by james-work-account — APPROVED** [review]
Excellent!

**Pull request merged**
